function pewpew () {
    if (info.score() >= 0) {
        mySprite2 = sprites.create(img`
            .........................
            .........................
            .........................
            ....2c2b2aaaaaaaa........
            ...2c2b2a................
            ..2c2b2a.8.8.8.8.........
            .2c2b2a.8.8.8.8..........
            2c2b2a.8.8.8.8...........
            2c2b2a.8.8.8.8...........
            .2c2b2a.8.8.8.8..........
            ..2c2b2a.8.8.8.8.........
            ...2c2b2a................
            ....2c2b2aaaaaaaa........
            .........................
            .........................
            .........................
            `, SpriteKind.Projectile)
    }
    if (info.score() >= 15) {
        mySprite2 = sprites.create(img`
            .........................
            .........................
            .........................
            ....2c2b2aaaaaaaaaa......
            ...2c2b2a................
            ..2c2b2a.8.8.8.8.........
            .2c2b2a.8.8.8.8..........
            2c2b2a.8.8.8.8...........
            2c2b2a.8.8.8.8...........
            .2c2b2a.8.8.8.8..........
            ..2c2b2a.8.8.8.8.........
            ...2c2b2a................
            ....2c2b2aaaaaaaaaa......
            .........................
            .........................
            .........................
            `, SpriteKind.Projectile)
    }
    if (info.score() >= 30) {
        mySprite2 = sprites.create(img`
            .........................
            .........................
            .........................
            ....2c2b2aaaaaaaaaaaaaaaa
            ...2c2b2a................
            ..2c2b2a.8.8.8.8.........
            .2c2b2a.8.8.8.8..........
            2c2b2a.8.8.8.8...........
            2c2b2a.8.8.8.8...........
            .2c2b2a.8.8.8.8..........
            ..2c2b2a.8.8.8.8.........
            ...2c2b2a................
            ....2c2b2aaaaaaaaaaaaaaaa
            .........................
            .........................
            .........................
            `, SpriteKind.Projectile)
    }
    tiles.placeOnTile(mySprite2, tiles.getTileLocation(23, randint(1, 13)))
    mySprite2.setVelocity(speed, 0)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.Projectile, function (sprite, otherSprite) {
    game.over(false, effects.dissolve)
})
scene.onHitWall(SpriteKind.Projectile, function (sprite, location) {
    sprite.destroy(effects.fire, 100)
    pewpew()
    if (speed > -120) {
        speed += change
        change += -1
        info.changeScoreBy(1)
    } else {
        info.changeScoreBy(3)
    }
})
let mySprite2: Sprite = null
let change = 0
let speed = 0
let mySprite = sprites.create(img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . 8 8 8 . . . . . 
    . . . . . . 8 8 6 9 6 8 8 . . . 
    . . . . . 8 6 9 9 9 9 9 6 8 . . 
    . . . 8 8 6 9 9 7 9 7 9 9 8 . . 
    . . 8 6 9 9 9 9 7 9 7 9 9 6 8 . 
    . 8 6 9 9 9 7 9 9 9 9 9 7 9 6 8 
    . 8 9 9 9 9 7 7 7 7 7 7 7 9 9 8 
    . 8 6 9 9 9 9 9 9 9 9 9 9 9 6 8 
    . . 8 6 9 9 9 9 9 9 9 9 9 6 8 . 
    . . . 8 8 8 8 8 8 8 8 8 8 8 . . 
    `, SpriteKind.Player)
controller.moveSprite(mySprite, 125, 125)
mySprite.setBounceOnWall(true)
tiles.setTilemap(tilemap`level1`)
scene.cameraFollowSprite(mySprite)
speed = -70
pewpew()
pewpew()
pewpew()
change = -1
info.setScore(0)
